export const HASH_OPERATIONS = {
	put: {
		id: 'put',
		name: 'Put',
		needsKey: true,
		needsValue: true,
		oneLine: 'Hash the key, find its bucket, append or update the entry there.',
		motionPhrase: 'hash, find bucket, write',
		complexity: 'O(1) avg · O(n) worst',
	},
	get: {
		id: 'get',
		name: 'Get',
		needsKey: true,
		needsValue: false,
		oneLine: 'Hash the key, scan only the matching bucket chain for the entry.',
		motionPhrase: 'hash, scan, read',
		complexity: 'O(1) avg · O(n) worst',
	},
	delete: {
		id: 'delete',
		name: 'Delete',
		needsKey: true,
		needsValue: false,
		oneLine: 'Hash the key, locate the entry in its chain, unlink it.',
		motionPhrase: 'hash, locate, unlink',
		complexity: 'O(1) avg · O(n) worst',
	},
	resize: {
		id: 'resize',
		name: 'Resize',
		needsKey: false,
		needsValue: false,
		oneLine: 'Allocate a larger table and rehash every entry into its new bucket.',
		motionPhrase: 'allocate, rehash, redistribute',
		complexity: 'O(n) — amortized into inserts',
	},
};

export const HASH_OP_ORDER = ['put', 'get', 'delete', 'resize'];

export const HASH_MAP_PRESETS = [
	{
		id: 'collision-chain',
		label: 'Collision chain',
		intent: 'Several keys share buckets, so get scans a short linked list.',
		entries: [
			{ key: 'cat', value: '5' },
			{ key: 'zap', value: '9' },
			{ key: 'dog', value: '4' },
			{ key: 'ate', value: '8' },
			{ key: 'tea', value: '7' },
		],
		capacity: 7,
		operationId: 'get',
		key: 'ate',
		value: '8',
	},
	{
		id: 'resize-pressure',
		label: 'Resize pressure',
		intent: 'A high load factor sets up the cost of rehashing every entry.',
		entries: [
			{ key: 'red', value: '12' },
			{ key: 'tan', value: '18' },
			{ key: 'ivy', value: '21' },
			{ key: 'oak', value: '34' },
		],
		capacity: 5,
		operationId: 'resize',
		key: 'red',
		value: '12',
	},
	{
		id: 'update-existing',
		label: 'Update existing',
		intent: 'Put first searches the chain, then overwrites a matching key.',
		entries: [
			{ key: 'cat', value: '5' },
			{ key: 'zap', value: '9' },
			{ key: 'dog', value: '4' },
			{ key: 'tea', value: '7' },
		],
		capacity: 7,
		operationId: 'put',
		key: 'cat',
		value: '13',
	},
	{
		id: 'clean-miss',
		label: 'Clean miss',
		intent: 'A missing key still hashes to one bucket; no full-table scan is needed.',
		entries: [
			{ key: 'elm', value: '3' },
			{ key: 'ash', value: '6' },
			{ key: 'fir', value: '8' },
		],
		capacity: 11,
		operationId: 'get',
		key: 'fox',
		value: '0',
	},
];

export const HASH_PSEUDO = {
	put: [
		'hash = 7',
		'for each character of key:',
		'  hash = hash * 31 + characterCode',
		'index = hash % capacity',
		'scan bucket[index] for matching key',
		'if found: update value',
		'else: append (key, value) to chain',
	],
	get: [
		'hash = 7',
		'for each character of key:',
		'  hash = hash * 31 + characterCode',
		'index = hash % capacity',
		'scan bucket[index] for matching key',
		'return value if found, else miss',
	],
	delete: [
		'hash = 7',
		'for each character of key:',
		'  hash = hash * 31 + characterCode',
		'index = hash % capacity',
		'scan bucket[index] for matching key',
		'unlink the matching entry',
	],
	resize: [
		'pick a new capacity (next prime ≈ 2·old)',
		'allocate empty new table',
		'for each entry in old table:',
		'  index = hash % newCapacity',
		'  append entry to newTable[index]',
		'replace old table with newTable',
	],
};
